name: Build and deploy ASP.Net Core app to Azure Web App - perosnality

on:
  push:
    branches:
      - add-more-images
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish -c Release -o publish

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_42000B3C8EF1411D992E43D9E4D77B68 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CA441F3C8B3040E0836AAC96CF03D008 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_10B50EC1BF6245918D59AF2A1DB45BC5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'perosnality'
          slot-name: 'Production'
          package: .
